repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.2
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-r", "src/", "--severity-level", "high"]
        additional_dependencies: ["bandit[toml]"]
        pass_filenames: false
